export const CONFIG = {
  AI: {
    MODEL: "gemini-2.5-flash",
    MAX_DESCRIPTION_LENGTH: 8000,
    MAX_RAW_DESCRIPTION: 5000,
    RESUME_SUMMARY_MAX: 500,
    RESUME_EXPERIENCE_MAX: 10,
    COVER_LETTER_MIN_WORDS: 200,
    COVER_LETTER_MAX_WORDS: 400,
    INTERVIEW_QUESTIONS_COUNT: 15,
    INTERVIEW_QUESTIONS_MAX: 20,
  },
  SCRAPER: {
    TIMEOUT: 10000,
    MAX_RETRIES: 3,
    RETRY_DELAY: 1000,
    USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  SCORING: {
    MIN_SCORE: 0,
    MAX_SCORE: 100,
  },
};
